import * as z from "zod";
import type { CryptoContext } from "@pagopa/io-react-native-jwt";
import type { SupportedSdJwtLegacyFormat } from "../../../sd-jwt/types";
import type { jsonWebKeySet } from "@pagopa/io-wallet-oid-federation";

export type PresentationParams = z.infer<typeof PresentationParams>;
export const PresentationParams = z.object({
  client_id: z.string().nonempty(),
  request: z.string().optional(),
  request_uri: z.string().url().optional(),
  request_uri_method: z.enum(["get", "post"]).optional(),
  state: z.string().optional(),
});

export type WalletMetadata = z.infer<typeof WalletMetadata>;
export const WalletMetadata = z.object({
  authorization_endpoint: z.string().url(),
  client_id_schemes_supported: z.array(z.string()).optional(),
  client_id_prefixes_supported: z.array(z.string()).optional(),
  response_types_supported: z.array(z.string()).optional(),
  response_modes_supported: z.array(z.string()).optional(),
  request_object_signing_alg_values_supported: z.array(z.string()).optional(),
  vp_formats_supported: z.record(
    z.string(),
    z.object({
      "sd-jwt_alg_values": z.array(z.string()).optional(), // alg_values_supported?
    })
  ),
});

/**
 * Wallet capabilities that must be submitted to get the Request Object
 * via POST request when the `request_uri_method` is `post`.
 */
export type RequestObjectWalletCapabilities = z.infer<
  typeof RequestObjectWalletCapabilities
>;
export const RequestObjectWalletCapabilities = z.object({
  wallet_metadata: WalletMetadata,
  wallet_nonce: z.string().optional(),
});

/**
 * This type models the possible error responses the OpenID4VP protocol allows for a presentation of a credential.
 * When the Wallet encounters one of these errors, it will notify the Relying Party through the `response_uri` endpoint.
 * See https://italia.github.io/eid-wallet-it-docs/versione-corrente/en/pid-eaa-presentation.html#authorization-response-errors for more information.
 */
export type ErrorResponse = z.infer<typeof ErrorResponse>;
export const ErrorResponse = z.enum([
  "invalid_request_object",
  "invalid_request_uri",
  "vp_formats_not_supported",
  "invalid_request",
  "access_denied",
  "invalid_client",
]);

export type AuthorizationResponse = {
  redirect_uri?: string;
};

/**
 * A object that associate the information needed to multiple remote presentation
 * Used with DCQL queries
 */
export type RemotePresentationDetails = {
  requestedClaims: string[];
  credentialId: string;
  vpToken: string;
};

type ClientMetadata = {
  jwks: jsonWebKeySet;
  encrypted_response_enc_values_supported: string[];
  client_id: string;
  client_name: string;
  logo_uri: string;
  application_type: "web";
  request_uris: string[];
  response_uris: string[];
  vp_formats_supported: Record<string, { "sd-jwt_alg_values"?: string[] }>;
};

/**
 * Common Request Object type, decoupled from specific IT-Wallet versions
 */
export type RequestObject = {
  iss: string;
  response_uri: string;
  nonce: string;
  state: string;
  client_id: string;
  dcql_query: Record<string, unknown>;
  response_type: "vp_token";
  response_mode: "direct_post.jwt";
  x5c?: string[];
  trust_chain?: string[];
  client_metadata?: ClientMetadata;
};

/**
 * A object that associate the information needed to multiple remote presentation
 */
export type RemotePresentation = {
  presentations: {
    requestedClaims: string[];
    credentialId: string;
    format: string;
    vpToken: string;
  }[];
  generatedNonce?: string /* nonce generated by app, used in mdoc presentation */;
};

/**
 * A pair that associate a key tag with a credential, used in DCQL queries
 */
export type Credential4Dcql = [string /* keyTag */, string /* credential */];

/**
 * An object that defines claims to disclose. Nested claims must use a nested structure.
 * @example { name: true, address: { country: true } }
 */
export type PresentationFrame = {
  [k: string]: boolean | undefined | PresentationFrame;
};

/**
 * A pair that associate a tokenized Verified Credential with the claims presented or requested to present.
 */
export type Presentation = [
  /* verified credential token */ string,
  /* claims */ PresentationFrame,
  /* the context for the key associated to the credential */ CryptoContext,
];

export type CredentialFormat =
  | { format: "dc+sd-jwt"; vct: string }
  | { format: SupportedSdJwtLegacyFormat; vct: string }
  | { format: "mso_mdoc"; doctype: string };

export type EvaluatedDisclosure = {
  namespace?: string;
  name: string;
  value: unknown;
};
