# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build a new APK in release mode"
  lane :build_apk do |options|
    # # Increase version code and version name and build an APK in release mode 
    # increment_version_code(app_project_dir: '**/app')
    # increment_version_name(app_project_dir: '**/app', bump_type: options[:bump_type])

    android_set_version_name(
      version_name: options[:version]
    )
    
    gradle(
      task: ":app:assembleRelease",
    )
  end
end

