import * as z from "zod";

const url = z.string().url();

const envSchema = z.object({
  EXPO_PUBLIC_PRE_GOOGLE_CLOUD_PROJECT_NUMBER: z.string().min(1),
  EXPO_PUBLIC_PRE_LOGGING_SERVER: url,
  EXPO_PUBLIC_PRE_REDIRECT_URI: url,
  EXPO_PUBLIC_PRE_VERIFIER_BASE_URL: url,
  EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_0: url,
  EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_3: url,
  EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_0: url,
  EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_3: url,
  EXPO_PUBLIC_PRE_WALLET_PROVIDER_BASE_URL: url,
  EXPO_PUBLIC_PRE_WALLET_TA_BASE_URL: url,
  EXPO_PUBLIC_PRE_X509_CERT_ROOT: z.string().min(1),
  EXPO_PUBLIC_PROD_GOOGLE_CLOUD_PROJECT_NUMBER: z.string().min(1),
  EXPO_PUBLIC_PROD_LOGGING_SERVER: url,
  EXPO_PUBLIC_PROD_REDIRECT_URI: url,
  EXPO_PUBLIC_PROD_VERIFIER_BASE_URL: url,
  EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_0: url,
  EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_3: url,
  EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_0: url,
  EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_3: url,
  EXPO_PUBLIC_PROD_WALLET_PROVIDER_BASE_URL: url,
  EXPO_PUBLIC_PROD_WALLET_TA_BASE_URL: url,
  EXPO_PUBLIC_PROD_X509_CERT_ROOT: z.string(),
});

export type ExpoEnvironment = z.infer<typeof envSchema>;

const rawEnv = {
  EXPO_PUBLIC_PRE_GOOGLE_CLOUD_PROJECT_NUMBER:
    process.env.EXPO_PUBLIC_PRE_GOOGLE_CLOUD_PROJECT_NUMBER,
  EXPO_PUBLIC_PRE_LOGGING_SERVER: process.env.EXPO_PUBLIC_PRE_LOGGING_SERVER,
  EXPO_PUBLIC_PRE_REDIRECT_URI: process.env.EXPO_PUBLIC_PRE_REDIRECT_URI,
  EXPO_PUBLIC_PRE_VERIFIER_BASE_URL:
    process.env.EXPO_PUBLIC_PRE_VERIFIER_BASE_URL,
  EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_0:
    process.env.EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_0,
  EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_3:
    process.env.EXPO_PUBLIC_PRE_WALLET_EAA_PROVIDER_BASE_URL_V1_3,
  EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_0:
    process.env.EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_0,
  EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_3:
    process.env.EXPO_PUBLIC_PRE_WALLET_PID_PROVIDER_BASE_URL_V1_3,
  EXPO_PUBLIC_PRE_WALLET_PROVIDER_BASE_URL:
    process.env.EXPO_PUBLIC_PRE_WALLET_PROVIDER_BASE_URL,
  EXPO_PUBLIC_PRE_WALLET_TA_BASE_URL:
    process.env.EXPO_PUBLIC_PRE_WALLET_TA_BASE_URL,
  EXPO_PUBLIC_PRE_X509_CERT_ROOT: process.env.EXPO_PUBLIC_PRE_X509_CERT_ROOT,
  EXPO_PUBLIC_PROD_GOOGLE_CLOUD_PROJECT_NUMBER:
    process.env.EXPO_PUBLIC_PROD_GOOGLE_CLOUD_PROJECT_NUMBER,
  EXPO_PUBLIC_PROD_LOGGING_SERVER: process.env.EXPO_PUBLIC_PROD_LOGGING_SERVER,
  EXPO_PUBLIC_PROD_REDIRECT_URI: process.env.EXPO_PUBLIC_PROD_REDIRECT_URI,
  EXPO_PUBLIC_PROD_VERIFIER_BASE_URL:
    process.env.EXPO_PUBLIC_PROD_VERIFIER_BASE_URL,
  EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_0:
    process.env.EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_0,
  EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_3:
    process.env.EXPO_PUBLIC_PROD_WALLET_EAA_PROVIDER_BASE_URL_V1_3,
  EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_0:
    process.env.EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_0,
  EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_3:
    process.env.EXPO_PUBLIC_PROD_WALLET_PID_PROVIDER_BASE_URL_V1_3,
  EXPO_PUBLIC_PROD_WALLET_PROVIDER_BASE_URL:
    process.env.EXPO_PUBLIC_PROD_WALLET_PROVIDER_BASE_URL,
  EXPO_PUBLIC_PROD_WALLET_TA_BASE_URL:
    process.env.EXPO_PUBLIC_PROD_WALLET_TA_BASE_URL,
  EXPO_PUBLIC_PROD_X509_CERT_ROOT: process.env.EXPO_PUBLIC_PROD_X509_CERT_ROOT,
};

let env: ExpoEnvironment | null = null;

export const initEnv = (): void => {
  if (env) {
    return;
  }

  const parsed = envSchema.safeParse(rawEnv);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map(({ message, path }) => `${path.join(".")}: ${message}`)
      .join("\n");
    throw new Error(`Invalid environment variables:\n${issues}`);
  }

  env = parsed.data;
};

export const getEnv = (): ExpoEnvironment => {
  if (!env) {
    throw new Error(
      "Environment not validated. Call initEnv() during application startup.",
    );
  }

  return env;
};
